version: '3.8'

services:
  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      # Update these variables based on your configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/realtime-emergency-response-alert-system-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: realtime-emergency-response-alert-system-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"  # Controller listener port for KRaft mode
    environment:
      # Enable KRaft mode by setting the process roles (broker and controller)
      KAFKA_PROCESS_ROLES: "broker,controller"
      # Unique node id
      KAFKA_NODE_ID: 1
      # Define controller quorum with one node (adjust host/port as needed)
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      # Define the listeners for both broker and controller
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      # Advertise the broker listener (clients connect here)
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      # Specify the controller listener names
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # Set the offsets topic replication factor
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
